# Generated by Django 5.1.3 on 2024-12-04 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_base_value_item_selling_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='selling_price',
            new_name='sell_price',
        ),
    ]
