# Generated by Django 5.1.3 on 2024-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_selling_price_item_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
