# Generated by Django 5.1.3 on 2024-11-28 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('keep_after_action', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActionReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('drop_rate', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.IntegerField()),
                ('action_type', models.CharField(choices=[('COMBAT', 'COMBAT'), ('GATHER', 'GATHER'), ('CRAFT', 'CRAFT')], max_length=10)),
                ('experience', models.FloatField()),
                ('duration', models.FloatField()),
                ('combat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='combat.enemy')),
            ],
        ),
    ]
