# Generated by Django 5.1.3 on 2024-11-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_action_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='translations',
            field=models.JSONField(default=dict),
        ),
    ]
