POST http://localhost:8000/api/token/
Content-Type: application/json

{
  "username": "Vidski5",
  "password": "Alphagunlol!339"
}

> {%
    client.global.set("auth_token", response.body.access);
%}


###

POST http://localhost:8000/api/start-action/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "skill_id": 1,
  "action_id": 1
}

###

POST http://localhost:8000/api/stop-action/
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###

GET http://localhost:8000/api/me/
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###

GET http://localhost:8000/api/items/
Content-Type: application/json
Authorization: Bearer {{auth_token}}



###

POST localhost:8000/api/buy-item/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": 1,
  "quantity": 10
}


###

POST localhost:8000/api/sell-item/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": 1,
  "quantity": 10
}